---
- hosts: all
  gather_facts: false
  tasks:
  - name: Gather the package facts
    package_facts: 
      manager: apt
    no_log: true
#  - name: Put in database if mysql-server is installed
#    uri:
#      url: http://10.15.15.86:2379/v2/keys/mysql-ver/{{ inventory_hostname }}
#      method: PUT
#      body: "value={{ item.value[0]['version'] }}&ttl=7200"
#      status_code: 201
#      return_content: yes
#      headers:
#        Content-Type: "application/x-www-form-urlencoded"
#    when: "'mysql-server' in item.key"
#    loop: "{{ ansible_facts.packages | dict2items }}"
#    ignore_errors: True
  - name: test_package
    debug: 
      msg: "{{ item.value[0] }}"
#      msg: "{{ inventory_hostname }}, {{ ansible_facts | json_query('packages.mysql-server-[*].name') }}"
#      msg: "{{ inventory_hostname }}, {{ ansible_facts.packages['mysql-server'][0]['version'] }}"
    when: "'mysql' in item.key"
    loop: "{{ ansible_facts.packages | dict2items }}"
    loop_control:
      label: "{{ item.key }}"