---
- hosts: all
  gather_facts: false
  tasks:
  - name: Gather the package facts
    package_facts: 
      manager: apt
  - name: Curl is not installed
    debug:
      msg: "{{ inventory_hostname }}, Curl not installed."
    when: "'curl' not in ansible_facts.packages"
  - name: Curl is installed
    debug: 
      msg: "{{ inventory_hostname }}, {{ ansible_facts.packages['curl'] }}"
    when: "'curl' in ansible_facts.packages"
