---
- hosts: all
  gather_facts: false
  tasks:
  - name: get hostnames
    command: hostname
    register: output
    ignore_errors: True
  - name: Put in database
    uri:
      url: http://10.15.15.86:2379/v2/keys/hostnames/{{ inventory_hostname }}
      method: PUT
      body: "value={{ output.stdout }}&ttl=28800"
      status_code: 201
      return_content: yes
      headers:
        Content-Type: "application/x-www-form-urlencoded"
    register: curl_out
    ignore_errors: True

