---
- hosts: 10.10.20.222
  gather_facts: false
  tasks:
  - name: Check whether /app/tomcat/conf/server.xml exists
    stat:
      path: /app/tomcat8/conf/server.xml
    check_mode: yes
    changed_when: false
    register: filecheck

  - name: Change logging pattern in /app/tomcat/conf/server.xml file
    replace:
      path: /app/tomcat8/conf/server.xml
      regexp: "Unattended-Upgrade \"1\""
      replace: "Unattended-Upgrade \"0\""
    when: filecheck.stat.exists
    

#  - name: Check whether Unattended-Upgrade present in file
#    lineinfile:
#      path: /etc/apt/apt.conf.d/10periodic
#      regexp: "Unattended-Upgrade \"1\""
#      state: absent
#    check_mode: yes
#    changed_when: false
#    register: conf
#    when: filecheck.stat.exists
#
#  - name: Add line  in /etc/apt/apt.conf.d/10periodic
#    lineinfile:
#      path: /etc/apt/apt.conf.d/10periodic
#      line: 'APT::Periodic::Unattended-Upgrade "0";'
#      insertafter : EOF
#    when: 
#      - not filecheck.stat.exists
#      - not conf.found
