---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: Make sure the agent started up and connected to the right collector
    wait_for:
      path: /var/lib/tomcat8/newrelic/logs/newrelic_agent.log
      search_regex: Failed to connect to localhost:443 for Tomcat Molecule test
      timeout: 30
