---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:18.04
    pre_build_image: False
    privileged: True
provisioner:
  name: ansible
verifier:
  name: ansible
