---
- name: Converge
  hosts: all
  tasks:
    - name: "Include newrelic-java-agent"
      include_role:
        name: "newrelic-java-agent-ansible-role"
      vars:
        nr_java_agent_config:
          license_key: YOUR_LICENSE_KEY
          app_name: Tomcat Molecule test
          collector_host: localhost

        server_type: tomcat
        server_root: /var/lib/tomcat8
        jvm_conf_file: /usr/share/tomcat8/bin/setenv.sh
        server_user: tomcat8
        server_group: tomcat8
        service_name: tomcat8
        restart_web_server: false
